---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Install Docker
      block:
        - name: Adding universe
          apt_repository:
            repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main
            state: present
        - name: Installing additional package
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            cache_valid_time: 86400
            state: present
        - name: Adding Docker's key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Settting up stable repository 
          apt_repository: 
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
              https://download.docker.com/linux/ubuntu 
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker
        - name: Installing Docker-ce
          apt:
            name: docker-ce
            update-cache: true
        - name: Checking  the docker service
          service:
            name: docker
            state: restarted
            enabled: true
      become: true 
    - name: Install Docker-compose
      block:
        - name: Getting latest version Docker-compose 
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest 
            body_format: json
          register: page
        - name: Installing Docker-compose 
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true
    - name: Completing the installation
      block: 
        - name: Adding a user to the docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
        - name: Rebooting 
          reboot:
      become: true
            